### PR TITLE
Here are some changes

### PR DESCRIPTION
**Pull request by EpicSteve33**
1st commit adds if player is in arena cannot chat with other worlds, I will improve this later

### CODE REVIEW

**Comment by EpicSteve33** [comment]
2nd commit adds sounds on countdown and xp on countdown

**Comment by Dev-Kevo** [comment]
2nd sounds good

**Comment by EpicSteve33** [comment]
Why not chat event

**Comment by EpicSteve33** [comment]
It's makes the plugin more like lbsg

**Comment by EpicSteve33** [comment]
I will make a config thing to disable it later

**Comment by remotevase** [comment]
THANK YOU SO MUCH FOR FIXING CHAT!!!!!!!!!

**Comment by EpicSteve33** [comment]
It's still not %100 @remotevase 

Players in non SG worlds can still chat with SG players, but they cannot see what SG players say
I will fix this later

**Comment by EpicSteve33** [comment]
I'll add like a per world chat with a config on/off option

**Comment by ImagicalGamer** [comment]
I'll fix it :wink:

**Comment by EpicSteve33** [comment]
Nice👍

**Comment by EpicSteve33** [comment]
@ImagicalGamer you should make a gutter.im chat

**Comment by EpicSteve33** [comment]
@remotevase @ImagicalGamer @RedEnder we all can chat here https://gitter.im/EpicSteve33/SurvivalGames

**Pull request merged**
