### PR TITLE
Possibly fixed error

### PR DESCRIPTION
**Pull request by EpicSteve33**
Removed line 621 - 636 hopefully it will work :)

### CODE REVIEW

**Comment by ImagicalGamer** [comment]
@remotevase this is up to you.

**Comment by Taki21** [comment]
That will help but for remote vase to keep it i have a strategy.
@remotevase Do uu mind bro?

**Comment by remotevase** [comment]
I want to merge, but lemme do something first

**Comment by remotevase** [comment]
okay, merging. I kept the code in file "unstable file"

**Comment by Taki21** [comment]
Ok then nvm

**Pull request merged**
