### PR TITLE
Send the Armor contents so annoying when u cant see the armor

### PR DESCRIPTION
**Pull request by RedEnder**
Send the Armor contents

### CODE REVIEW

**Comment by ImagicalGamer** [comment]
@remotevase think it would work?

**Comment by RedEnder** [comment]
@ImagicalGamer This code worked last time i used it

**Comment by ImagicalGamer** [comment]
Ok merging pull request =D.

**Comment by remotevase** [comment]
@ImagicalGamer don't ask me. Very inactive due to state testing. But, yeah, should work

**Pull request merged**
