### PR TITLE
Update SurvivalGamesV3.php

### PR DESCRIPTION
**Pull request by erkam2002**
?

### CODE REVIEW

**Comment by remotevase** [comment]
@ImagicalGamer if the latest commit fails, we should try this

**Comment by erkam2002** [comment]
test it pls

**Comment by remotevase** [comment]
are you sure this works?

**Comment by erkam2002** [comment]
idk it can work

**Comment by remotevase** [comment]
we will test it, just wait a short while...

**Comment by erkam2002** [comment]
ok

**Comment by erkam2002** [comment]
if this not work test this : if($this->noDamageTicks > 300){

**Comment by remotevase** [comment]
hmm okay

**Pull request merged**
