### PR TITLE
added some new messages and more...

### PR DESCRIPTION
**Pull request by EpicSteve33**
Grace works really well so I added a message to let players know, also winner message should look better now 

I tested these many times before I added them

### CODE REVIEW

**Comment by EpicSteve33** [comment]
I also added a cool count down from 30 seconds to 1 second

I reused code from the plugin btw

**Comment by remotevase** [comment]
Good job. Just gonna change one thing

**Comment by EpicSteve33** [comment]
ok should I add sounds like lbsg has cuz in my version I did

**Comment by remotevase** [comment]
yes, please

**Comment by EpicSteve33** [comment]
ok ill open a new pull in a few min

**Comment by EpicSteve33** [comment]
@ImagicalGamer  @remotevase can you help me add a "You Are no longer invincible!" Message I know what time it needs to be displayed `if($time <= 750)` I just cannot get it to work

**Comment by ImagicalGamer** [comment]
@EpicSteve33 Yea I can add it if you didn't in your pull request

**Comment by EpicSteve33** [comment]
no I haven’t added it because I cant get it to work

**Comment by remotevase** [comment]
I'll add it, ig @ImagicalGamer you haven't yet

**Comment by EpicSteve33** [comment]
@remotevase this is the code I've used but it crashes idk y I'm probably not seeing my error

```
else if($time2 == 750){
 									
 									foreach($playersArena as $pl)
 									{
 										$pl->sendMessage($this->prefix . "Grace Period has ended!");
                                                                                  $level=$pl->getLevel();
                                                                                 $level->addSound(new PopSound($pl));
 									}	
 									
								}
```

**Comment by remotevase** [comment]
I'm not sure. Can you show me the code before that please?

**Comment by EpicSteve33** [comment]
```
	$time--;
								if($time>=180)
								{
								$time2 = $time - 180;
								$minutes = $time2 / 60;
									/*foreach($playersArena as $pl)
									{
										$pl->sendPopup($this->prefix . $time2 . " left in the match!");
									}*/
								if(is_int($minutes) && $minutes>0)
								{
									foreach($playersArena as $pl)
									{
										$pl->sendMessage($this->prefix . $minutes . " minutes to deathmatch");
										$level=$pl->getLevel();
										$level->addSound(new PopSound($pl));
									}
								}
								else if($time2 == 300)
								{
									foreach($playersArena as $pl)
									{
										$pl->sendMessage($this->prefix . "The chests have been refilled!");
                                                                                $level=$pl->getLevel();
                                                                                $level->addSound(new PopSound($pl));
									}
									$this->refillChests($levelArena);
								}
								else if($time2 == 750){
									
									foreach($playersArena as $pl)
									{
										$pl->sendMessage($this->prefix . "Grace Period has ended!");
                                                                                $level=$pl->getLevel();
                                                                                $level->addSound(new PopSound($pl));
									}	
									
								}
								else if($time2 == 30 || $time2 == 15 || $time2 == 10 || $time2 ==5 || $time2 ==4 || $time2 ==3 || $time2 ==2 || $time2 ==1)
								{
									foreach($playersArena as $pl)
									{
										$pl->sendMessage($this->prefix . $time2 . " seconds to deathmatch");
										$level=$pl->getLevel();
										$level->addSound(new PopSound($pl));
									}
								}
								if($time2 <= 0)
								{
									$spawn = $levelArena->getSafeSpawn();
									$levelArena->loadChunk($spawn->getX(), $spawn->getZ());
									foreach($playersArena as $pl)
									{
										$pl->teleport($spawn,0,0);
									}
								}
								}
```

**Comment by ImagicalGamer** [comment]
lol @remotevase I got sidetracked, I'm working on a core for 4LifeCraft.

**Comment by EpicSteve33** [comment]
@ImagicalGamer do you think my code will work?

**Comment by ImagicalGamer** [comment]
I think it should work, test it.

**Comment by EpicSteve33** [comment]
When I tested it I seen no message also got no errors that why I need yalls help lep

**Comment by EpicSteve33** [comment]
Lel

**Comment by ImagicalGamer** [comment]
Did you re define $time2? Or used what we had?

**Comment by EpicSteve33** [comment]
I placed it in the already used area

**Comment by EpicSteve33** [comment]
if($time>=180)
                                {
                                $time2 = $time - 180;
                                $minutes = $time2 / 60;
                                    /*foreach($playersArena as $pl)
                                    {
                                        $pl->sendPopup($this->prefix . $time2 . " left in the match!");
                                    }*/
                                if(is_int($minutes) && $minutes>0)
                                {
                                    foreach($playersArena as $pl)
                                    {
                                        $pl->sendMessage($this->prefix . $minutes . " minutes to deathmatch");
                                        $level=$pl->getLevel();
                                        $level->addSound(new PopSound($pl));
                                    }
                                }

**Comment by EpicSteve33** [comment]
Idk why It wont work

**Comment by EpicSteve33** [comment]
@remotevase @ImagicalGamer I did it fully Tested too :) https://github.com/ImagicalGamer/SurvivalGamesV3/pull/119

**Pull request merged**
