### PR TITLE
MinePlex Popup style

### PR DESCRIPTION
**Pull request by CristaudoORG**

### CODE REVIEW

**Comment by remotevase** [comment]
I will not merge this exactly, but I will commit something similar. 
DO NOT MERGE!!
LEAVE THIS PR OPEN!!
DO NOT QUESTION THESE 2 DECISIONS

**Comment by ImagicalGamer** [comment]
OK

**Comment by remotevase** [comment]
Gimme a few hours and I will work on it

**Comment by remotevase** [comment]
see #8fcaa60

**Pull request closed without merging**
