### PR TITLE
Made some Changes 

### PR DESCRIPTION
**Pull request by EpicSteve33**
While players are waiting the can move but not leave the spot

### CODE REVIEW

**Comment by EpicSteve33** [comment]
I tested this on ImagicalMine but I didn't test it on genisys yet, but it works pretty well on ImagicalMine

**Comment by EpicSteve33** [comment]
Oops lol

**Comment by Driesboy** [comment]
nice fixed

**Comment by XiangZhao969** [comment]
@EpicSteve33 where can you download IM?

**Comment by EpicSteve33** [comment]
@XiangZhao969 from github, I also use genisys but not often

**Comment by XiangZhao969** [comment]
@EpicSteve33 download src then /makeserver?

**Comment by EpicSteve33** [comment]
@XiangZhao969  I downloaded the src then dropped it into my sever folder and started my server (you need php7)

**Comment by EpicSteve33** [comment]
@XiangZhao969 this isn't where I want to chat please go open a issue on ImagicalMine if you cannot figure your problem out sorry :(

**Comment by XiangZhao969** [comment]
it doesn't require .phar file?

**Comment by EpicSteve33** [comment]
@XiangZhao969  On pc no it doesn't on android/iOS

**Comment by XiangZhao969** [comment]
Sorry and thank you for the replies :p because IM members don't help me and always close my issues

**Comment by EpicSteve33** [comment]
@XiangZhao969 it's fine I 100% understand they do the same to me sometimes but if you have anymore questions please contact me on kik or Twitter @epicsteve33

**Comment by XiangZhao969** [comment]
Thank you :D

**Comment by remotevase** [comment]
Maybe I will add this, but will not merge it. I like the idea (basically the grace period)

**Comment by EpicSteve33** [comment]
Wut?

**Comment by EpicSteve33** [comment]
Why not merge? Cuz if it's the lightning is a problem I'll remove it

**Comment by EpicSteve33** [comment]
All of it was tested and works with ImagicalMine

**Comment by remotevase** [comment]
Oh, thats wht you added!

**Comment by remotevase** [comment]
Actually, you didn't test it on ImagicalMine because the code that you provided caused a crash. I fixed it now, but in the future please do not lie about testing it

**Comment by EpicSteve33** [comment]
I did not lie about testing, yes I know It crashes I forgot to change some stuff

**Comment by EpicSteve33** [comment]
I have been very busy lately so when I added this I was in a hurry sorry bout that but anyway Your welcome I'm glad I can be of some help

**Pull request merged**
