### PR TITLE
fix #128

### LINKED ISSUE #128: Quit Event
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

So if a player leaves the match by logging out or if they die and leave the plugin still thinks they are in a match and nobody wins if the counter hits 0 it's kinda annoying, I think to fix this we need to add a quit event. This issue also happens when a player doesn't respawn

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by remotevase** [comment]
This doesnt do much, does it?

**Comment by remotevase** [comment]
I don't see any major changes done here, other than reorganizing some stuff to make the gameplay smoother

**Comment by remotevase** [comment]
I'll merge it anyways. I hope that it doesnt crash...

**Comment by Driesboy** [comment]
I think i will work

**Pull request merged**
