### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by ImagicalGamer** [comment]
Thanks, I didn't notice that.

**Comment by erkam2002** [comment]
xD

**Comment by MacHupTR** [comment]
@erkam2002 
screenshot_2016-03-13-15-34-38-1

Böyle hata alıyorum neden

**Comment by erkam2002** [comment]
En yenisini kulan buradan download et ve buradan phar yap yine dene  http://pmt.mcpe.me/

**Comment by erkam2002** [comment]
Hangi software kullaniyorzun imagical yoksa genisys?

**Comment by ImagicalGamer** [comment]
So he didn't compile it before adding it to the server? Don't use the one from this repo, use the one from ImagicalMine forums. The code on this repo isn't finished yet.

**Comment by MacHupTR** [comment]
@erkam2002  imagical kullaniyom

**Comment by remotevase** [comment]
Using imagicalmine? So then it shouldn't crash unless, like @ImagicalGamer said, you compiled the code from this repo

**Comment by ImagicalGamer** [comment]
Use [THIS](http://forums.imagicalmine.net/plugins/survivalgames.68/) it is bug free for ImagicalMine. It will not run on Genisys.

**Comment by erkam2002** [comment]
Ozaman bunu all http://forums.imagicalmine.net/plugins/survivalgames.68/

**Pull request closed without merging**
