### PR TITLE
 Fix grace period

### PR DESCRIPTION
**Pull request by Dev-Kevo**
"if ($config->get($level . "PlayTime") > 750)"this is 
the end of grace. Players will be able to hit each other.
Only thing that need to be added is the sendmessage that grace started and ended

THIS WAS TESTED BY ME I CONFIRM THAT IT WORKS
if u don't believe me try it your self
Grace time is 15 sec once game starts

### CODE REVIEW

**Comment by Taki21** [comment]
YEs! But can u put another commit that makes it like 30 seconds? that will be amazing and I cant merge only @ImagicalGamer  and @remotevase can do it...

**Comment by Dev-Kevo** [comment]
Lol just change the 730

**Comment by ImagicalGamer** [comment]
@Dev-Kovo do you have a server we can test this on?

**Comment by Dev-Kevo** [comment]
Well it's personal and it not port

**Comment by ImagicalGamer** [comment]
Ah OK.

**Comment by ImagicalGamer** [comment]
@Driesboy can your server test?

**Comment by remotevase** [comment]
Seems like there would be no errors, and as @Taki21 said we wanna just make it 30 secs instead

**Comment by Dev-Kevo** [comment]
:/

**Pull request merged**
